### ISSUE TITLE
hi from gnark team :) 

### ISSUE THREAD

**Issue by gbotrel** [Veridise/picus_gnark#2]
Hi!

This repo looks interesting :) .

However, couldn't manage to run the example in the README.md. Seems the "grammar" for the ".sr1cs" file is not present on the main branch of picus? 

If all works well, it may be more elegant to have something that consume a `gnark.R1CS` as input rather than adding annotations; for example:

```
r1cs, ... := Compile(...) // gnark
p := picus.New(r1cs,...)
p.WriteTo(...)
```

If it's stable enough open to a PR into `gnark`;
* I suspect it will have some curve limitations?
* For groth16, we probably won't be able to support that when a circuit uses `api.Commit()` feature.

**Comment by gbotrel** [comment]
ha sorry realized we have a duplicate here https://github.com/Veridise/picus_gnark/issues/1 . Will close for now :)

**Comment by sorawee** [comment]
Thanks for the suggestion! 

Picus verifies that output variables are properly constrained (not underconstrained). However, if I understand correctly, "output variables" are not apparent from the Gnark circuit, which is why we need the extra annotation step.

Because of this, we want to be able to run control when the compilation happens (so that we can initialize data collection during the circuit compilation). That's why it needs to consume a circuit as an input. An alternative design is to provide a function `picus_gnark.Initialize` that users must call before calling `frontend.Compile`, but I think that's less elegant.

It would make sense to allow users to customize a field, however.
